### ISSUE TITLE
HW 1 Errors

### ISSUE THREAD

**Issue by NicholasAsirvadam** [OteyHaroldGitDataScientistUTA/IDS2024S#2]
Hello, the following are errors I have found in your first homework assignment:
1. You have not answered question 4.
2. You have not answered question 5.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.

**Comment by OteyHaroldGitDataScientistUTA** [comment]
I think I resolved the issue.

Thanks!

From: NicholasAsirvadam ***@***.***>
Date: Saturday, February 17, 2024 at 10:45 PM
To: OteyHaroldGitDataScientistUTA/IDS2024S ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OteyHaroldGitDataScientistUTA/IDS2024S] HW 1 Errors (Issue #2)

[External]

Hello, the following are errors I have found in your first homework assignment:

  1.  You have not answered question 4.
  2.  You have not answered question 5.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.
